--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.60.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2/2/2024 5:06:50 PM
-- Server version: 10.5.23
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE misa_webhaui_amis;

--
-- Drop procedure `Proc_InsertEmployee`
--
DROP PROCEDURE IF EXISTS Proc_InsertEmployee;

--
-- Drop procedure `Proc_UpdateEmployee`
--
DROP PROCEDURE IF EXISTS Proc_UpdateEmployee;

--
-- Drop table `employee`
--
DROP TABLE IF EXISTS employee;

--
-- Drop table `department`
--
DROP TABLE IF EXISTS department;

--
-- Set default database
--
USE misa_webhaui_amis;

--
-- Create table `department`
--
CREATE TABLE department (
  DepartmentId char(36) NOT NULL COMMENT 'khóa chính',
  DepartmentCode varchar(20) NOT NULL COMMENT 'mã phòng ban',
  DepartmentName varchar(255) NOT NULL COMMENT 'tên phòng ban',
  CreateDate date DEFAULT NULL COMMENT 'ngày tạo ',
  CreateBy varchar(255) DEFAULT NULL COMMENT 'người tạo',
  ModifileDate date DEFAULT NULL COMMENT 'ngày chỉnh sửa gần nhất',
  ModifileBy varbinary(255) DEFAULT NULL COMMENT 'người chỉnh sửa gần nhất',
  PRIMARY KEY (DepartmentId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci,
COMMENT = 'phòng ban ',
ROW_FORMAT = DYNAMIC;

--
-- Create table `employee`
--
CREATE TABLE employee (
  EmployeeId char(36) NOT NULL COMMENT 'khóa chính',
  EmployeeCode varchar(20) NOT NULL COMMENT 'mã nhân viên',
  EmployeeName varchar(100) NOT NULL COMMENT 'tên nhân viên',
  DateOfBrith date DEFAULT NULL COMMENT 'ngày sinh',
  Gender int(11) DEFAULT NULL COMMENT 'giới tính 0 nữ , 1 nam,2 chưa xác định',
  IdentityCode varchar(25) DEFAULT NULL COMMENT 'số chứng minh nhân dân',
  IdentityDate date DEFAULT NULL COMMENT 'ngày cấp',
  `Position` varchar(100) DEFAULT NULL COMMENT 'chức danh',
  IdentityPlace varchar(255) DEFAULT NULL COMMENT 'Nơi cấp',
  Address varchar(255) DEFAULT NULL COMMENT 'địa chỉ',
  PhoneNumber varchar(25) DEFAULT NULL COMMENT 'điện thoại di động',
  LandlinePhone varchar(25) DEFAULT NULL COMMENT 'điện thoại cố định',
  Email varchar(100) DEFAULT NULL COMMENT 'địa chỉ email',
  BankAccount varchar(25) DEFAULT NULL COMMENT 'tài khoản ngân hàng',
  BankName varchar(255) DEFAULT NULL COMMENT 'Tên ngân hàng',
  Branch varchar(255) DEFAULT NULL COMMENT 'chi nhánh',
  CreateDate date DEFAULT NULL COMMENT 'ngày tạo',
  CreateBy varchar(255) DEFAULT NULL COMMENT 'người tạo',
  ModifileDate date DEFAULT NULL COMMENT 'ngày chỉnh sửa gần nhất',
  ModifileBy varchar(255) DEFAULT NULL COMMENT 'Người chỉnh sửa gần nhất',
  DepartmentId char(36) DEFAULT NULL COMMENT 'khóa ngoài kết nối với bảng phòng ban',
  PRIMARY KEY (EmployeeId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci,
COMMENT = 'Danh mục nhân viên',
ROW_FORMAT = DYNAMIC;

--
-- Create index `EmployeeCode` on table `employee`
--
ALTER TABLE employee
ADD UNIQUE INDEX EmployeeCode (EmployeeCode);

--
-- Create foreign key
--
ALTER TABLE employee
ADD CONSTRAINT FK_employee_department FOREIGN KEY (DepartmentId)
REFERENCES department (DepartmentId) ON DELETE NO ACTION;

DELIMITER $$

--
-- Create procedure `Proc_UpdateEmployee`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE Proc_UpdateEmployee (IN mEmployeeId char(36),
IN mEmployeeCode varchar(20),
IN mEmployeeName varchar(100),
IN mDateOfBrith date,
IN mGender int,
IN mIdentityCode varchar(25),
IN mIdentityDate date,
IN mPosition varchar(100),
IN mIdentityPlace varchar(255),
IN mAddress varchar(255),
IN mPhoneNumber varchar(25),
IN mLandlinePhone varchar(25),
IN mEmail varchar(100),
IN mBankAccount varchar(25),
IN mBankName varchar(255),
IN mBranch varchar(255),
IN mCreateDate date,
IN mCreateBy varchar(255),
IN mModifyDate date,
IN mModifyBy varchar(255),
IN mDepartmentId char(36))
BEGIN
  UPDATE employee e
  SET EmployeeCode = mEmployeeCode,
      EmployeeName = mEmployeeName,
      DateOfBrith = mDateofBrith,
      Gender = mGender,
      IdentityCode = mIdentityCode,
      IdentityDate = mIdentityDate,
      `Position` = mPosition,
      IdentityPlace = mIdentityPlace,
      Address = mAddress,
      PhoneNumber = mPhoneNumber,
      LandlinePhone = mLandlinePhone,
      Email = mEmail,
      BankAccount = mBankAccount,
      BankName = mBankName,
      Branch = mBranch,
      CreateDate = mCreateDate,
      CreateBy = mCreateBy,
      ModifileDate = mModifyDate,
      ModifileBy = mModifyBy,
      DepartmentId = mDepartmentId
  WHERE e.EmployeeId = mEmployeeId;
END
$$

--
-- Create procedure `Proc_InsertEmployee`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE Proc_InsertEmployee (IN EmployeeId char(36), IN EmployeeCode varchar(20), IN EmployeeName varchar(100), IN DateOfBrith date, IN Gender int, IN IdentityCode varchar(25), IN IdentityDate date, IN `Position` varchar(100), IN IdentityPlace varchar(255), IN Address varchar(255), IN PhoneNumber varchar(25), IN LandlinePhone varchar(25), IN Email varchar(100), IN BankAccount varchar(25), IN BankName varchar(255), IN Branch varchar(255), IN CreateDate date, IN CreateBy varchar(255), IN ModifileDate date, IN ModifileBy varchar(255), IN ` DepartmentId` char(36))
BEGIN
  INSERT INTO employee (EmployeeId,
  EmployeeCode,
  EmployeeName,
  DateOfbrith,
  Gender,
  IdentityCode,
  IdentityDate,
  `Position`,
  IdentityPlace,
  Address,
  PhoneNumber,
  LandlinePhone,
  Email,
  BankAccount,
  BankName,
  Branch,
  CreateDate,
  CreateBy,
  ModifileDate,
  ModifileBy,
  DepartmentId)
    VALUES (EmployeeId,
    EmployeeCode,
    EmployeeName,
    DateOfBrith,
    Gender,
    IdentityCode,
    IdentityDate,
    `Position`,
    IdentityPlace,
    Address,
    PhoneNumber,
    LandlinePhone,
    Email,
    BankAccount,
    BankName,
    Branch,
    CreateDate,
    CreateBy,
    ModifileDate,
    ModifileBy,
    DepartmentId);

END
$$

DELIMITER ;

-- 
-- Dumping data for table department
--
INSERT INTO department VALUES
('20595ff5-b6e0-11ee-9729-f8477b936e6f', 'PB02', 'Phòng nhân sự', NULL, NULL, NULL, NULL),
('205a5f6a-b6e0-11ee-9729-f8477b936e6f', 'PB03', 'Phòng kế toán', NULL, NULL, NULL, NULL),
('205aa1b3-b6e0-11ee-9729-f8477b936e6f', 'PB04', 'Phòng đào tạo', NULL, NULL, NULL, NULL),
('9feafdd0-b6e0-11ee-9729-f8477b936e6f', 'PB01', 'Phòng hành chính', NULL, NULL, NULL, NULL),
('9febd839-b6e0-11ee-9729-f8477b936e6f', 'PB08', 'Phòng bảo vệ', NULL, NULL, NULL, NULL),
('9fec0b31-b6e0-11ee-9729-f8477b936e6f', 'PB07', 'Phòng lễ tấn', NULL, NULL, NULL, NULL),
('9fec44ae-b6e0-11ee-9729-f8477b936e6f', 'PB06', 'Phòng an ninh', NULL, NULL, NULL, NULL),
('b7b8c0f7-b6dd-11ee-9729-f8477b936e6f', 'PB05', 'Phòng chăm sóc khách hàng', NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table employee
--
INSERT INTO employee VALUES
('0682f9d1-6872-4d0c-977f-9a561017a098', 'NV-284', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '9feafdd0-b6e0-11ee-9729-f8477b936e6f'),
('070a978b-7625-4803-8562-43951f01676e', 'NV-203', 'Trần Sao Mai', '1998-04-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('087da7c2-05e9-48f0-99b3-4d69c5125b76', 'NV-168', 'Trần Sao Mai', '1998-04-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('08ca2829-263c-495e-bb25-e617b0d0ebc0', 'NV-156', 'Trần Sao Mai', '1998-03-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('09ca84cd-3739-4c7b-8c2b-f1899aa01d5f', 'NV-212', 'Nguyễn Minh Châu', '1999-08-03', 0, '', NULL, '', NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9febd839-b6e0-11ee-9729-f8477b936e6f'),
('0be7f5c8-3a32-422d-a733-2c9922afe8e5', 'NV-167', 'Trần Sao Mai', '1998-04-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('0dc24aa4-6412-41db-abd0-0d37cc00c010', 'NV-74', 'Hà Đức Chinh', '2000-01-01', 1, '03420987', '2024-01-29', 'Trưởng phòng', '', '', '', '', 'duc@gmail.com', '', '', '', NULL, NULL, NULL, NULL, '9feafdd0-b6e0-11ee-9729-f8477b936e6f'),
('0e0898f2-20c8-4a7f-9a65-d73065ceef90', 'NV-302', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('0e41f16e-81be-4bc8-837a-cb23c9e896fa', 'NV-140', 'Nguyễn Minh Châu', '1999-08-03', 0, '', NULL, '', NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('0f52be44-05c4-48e0-ac81-84b7b3e6f63d', 'NV-73', 'Hà Đức Chinh', '1999-01-01', 1, '', '2024-01-29', '', '', '', '', '', 'ducchinh2000@gmail.com', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('1148da8a-d203-4d09-9a61-db124a8d7960', 'NV-307', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('12aedd4b-e28d-4a5c-9c0a-32589c9dcacd', 'NV-90', 'Đào Thu Hằng', '2002-05-19', 0, '', NULL, '', NULL, NULL, NULL, NULL, 'hang99@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('1492a031-505d-4b95-a0f8-7cf9a71c85ed', 'NV-213', 'Trần Hoàng Sao Mai', '1998-04-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('164a2fc7-4a7c-4b4b-bd47-4467f7aa0d45', 'NV-30', 'Vũ Văn Thế', '2024-01-29', 1, '', '2024-02-05', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('176143a6-8c96-4491-9568-2332b5292622', 'NV-19', 'Trần Văn Huy', '2024-01-01', 1, '', '2024-01-29', '', '', '', '', '', 'hoan@gmail.com', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('18805330-092f-48d7-9e9e-1194b644ef12', 'NV-360', 'Nguyễn Minh Châu', NULL, 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('1a6703d6-68e3-4778-be44-55d02b5d455a', 'NV-100', 'Phạm Thái Dương', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9febd839-b6e0-11ee-9729-f8477b936e6f'),
('1b301de3-de6e-4082-9f9b-afa0e46ca790', 'NV-125', 'Nguyễn Minh Châu', '1999-08-03', 0, '', NULL, '', NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'b7b8c0f7-b6dd-11ee-9729-f8477b936e6f'),
('1c8c621e-06a1-417a-a864-8aaf5f0873e1', 'NV-248', 'Nguyễn Minh Châu', '2024-01-29', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('1caea8ac-2435-45bf-98d7-1664642aa817', 'NV-41', 'Trần Quốc Tuấn', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'tuangmailcom', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('1e075964-4715-4b36-b90b-f83f2446790d', 'NV-200', 'Ngô Gia Bảo', '2024-01-02', 1, '03420987', '2024-01-09', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '0989', 'hang99@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('1f6673c7-8b39-44b3-8137-322810ff4a9e', 'NV-58', 'Bùi Văn Sơn', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'sonbui@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('202ad5c5-6fc5-4545-a710-24239d4178c2', 'NV-166', 'Trần Sao Mai', '1998-04-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('20fb7627-461c-4785-b3f3-b37ec92f1150', 'NV-3', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('217c42d8-4cb7-4dbb-9c3a-9a596056897f', 'NV-149', 'Trần Sao Mai', '1998-02-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('22c645fb-0954-4ebc-9bd5-410126038e8f', 'NV-245', 'Trần Hoàng Sao Mai', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('230e6482-bbb3-4267-9131-ad595cc9c6b6', 'NV-65', 'Ngô Tất Sơn', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'son@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('24157631-5322-4841-98ef-11fa3d3eda25', 'NV-53', 'Bùi Anh Tú', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'anhtu@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('25161b07-85eb-43a6-a8ae-9271191b9011', 'NV-99', 'Phạm Đình Khiêm', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9febd839-b6e0-11ee-9729-f8477b936e6f'),
('2629f1f4-2fd4-4dcb-989c-7056b0f7928f', 'NV-153', 'Trần Sao Mai', '1998-02-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('296014bd-19c3-444c-ad45-60aefb310ade', 'NV-242', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-29', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('29e37eb7-da3a-4a98-b7e7-d04540da089a', 'NV-251', 'Nguyễn Minh Châu', NULL, 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('2b236031-2071-411d-90a2-865124256995', 'NV-205', 'Trần Hoàng Sao Mai', '1998-04-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('2b80b07c-f80e-4a81-a001-bd4492a74b3e', 'NV-147', 'Trần Thị Sao Mai', '1998-02-08', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('2d85f9dc-437a-4c02-bcf3-8b25caacaf0e', 'NV-97', 'Ngô Mạnh Hùng', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9fec44ae-b6e0-11ee-9729-f8477b936e6f'),
('2fb9e304-56f2-4280-897e-d5fdd944be31', 'NV-303', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('30c75c76-6e35-4707-990f-31037175f54b', 'NV-114', 'Trương Thành Hưng', '1998-02-04', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('30cbf8b0-f644-4f8a-8f55-f167a863c058', 'NV-127', 'Đỗ Ngọc Thúy', '1999-08-03', 0, '', NULL, '', '', '', '', '', 'thuydn@gmail.com', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('31706c52-afb8-4ea8-bc83-e4b84572d52e', 'NV-296', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('3207b3f1-6c7c-46fd-a73b-5e3d39bbe1a7', 'NV-62', 'Trần Văn Thế', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'thenv@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('33a27b1c-1ffd-40d4-bc21-e6201e80cfd7', 'NV-273', 'Nguyễn Minh Châu', '2000-01-22', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('3437e403-f030-4331-b2f4-fd9c38464f1f', 'NV-29', 'Vũ Văn Thế', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('35211720-6555-4f92-a01f-09342d190cb6', 'NV-148', 'Trần Thị Sao Mai', '1998-02-08', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('35702618-8c07-4c16-8571-45727f505127', 'NV-55', 'Nguyễn Khánh Huyền', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'khanhhuyen@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('3693ed3c-7c17-4265-b704-14647303a6a3', 'NV-89', 'Đào Thu Hằng', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'thuhang1905@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('377aa7e1-27c1-47c9-87d0-e2ac96a97e33', 'NV-54', 'Bùi Kim Anh ', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'anhkim@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('3aaeb6ac-7e3f-4f70-9082-443ad6cf54ac', 'NV-21', 'Ngô Văn Toàn', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hoan@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('3aba7a6f-a219-4f5b-bb75-80c4a3567446', 'NV-88', 'Hoàng Thị Sao Mai', '2002-04-30', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hoangmai@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('3af39c23-afe0-4d1a-9a8f-b293dffdf699', 'NV-06', 'Vũ Văn Thế 25', NULL, 1, '', NULL, '', NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('3b9f9a83-635a-4d61-b4eb-2e9c71c0bc6d', 'NV-27', 'Vũ Văn Thế', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hoang@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('3c89add8-a488-454d-b2da-fca40087a2a7', 'NV-35', 'Vũ Văn Thế', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('3ce9cf24-e1a4-448c-af74-09b3298c1d13', 'NV-400', 'Nguyễn Minh Châu', '2024-01-29', 0, '03425698', '2024-01-29', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('3e8e05cc-c049-4799-8948-0cfcbd29b453', 'NV-341', 'Hà Đức Chinh', '2000-01-01', 1, '03420987', '2024-01-29', 'Trưởng phòng', '', '', '', '', 'duc@gmail.com', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('4044ff5a-0f1d-44c4-996e-f9a0802561c5', 'NV-26', 'Vũ Văn Thế', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hoang@gmailcom', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('4057d32a-e970-4a90-a302-bdd4dd4cee2e', 'NV-361', 'Đỗ Ngọc Thúy', NULL, 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('422ac120-9c8c-4630-a1ce-738d89eec541', 'NV-216', 'Nguyễn Minh Châu', '2024-01-29', 0, '', '2024-01-29', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('449ffd91-dd3a-4efe-9e80-a82c9b243bfb', 'NV-72', 'Ngô Tất Sơn', '2020-08-18', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('45244cdf-ad9d-4f67-92d4-fab274a4feec', 'NV-48', 'Bùi Văn Sơn', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'sonbui@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('47a51ada-78ec-486d-8103-ec79446a0288', 'NV-112', 'Trương Thành Hưng', '1998-02-04', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('47c85a23-976e-4799-b5f5-edcdee8149de', 'NV-12', 'Trần Văn Huy', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('485918bf-b6e1-11ee-9729-f8477b936e6f', 'NV03', 'Nguyễn Thị Hoài', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'b7b8c0f7-b6dd-11ee-9729-f8477b936e6f'),
('48595ec3-b6e1-11ee-9729-f8477b936e6f', 'NV04', 'Đặng Trường Khánh', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9febd839-b6e0-11ee-9729-f8477b936e6f'),
('48943d98-2f14-4e95-84ff-20f4ecbbc548', 'NV-555', 'Bùi Văn Sơn', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'sonbui@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('49591725-1fdf-4c9d-8c00-f4720ba0862d', 'NV-20', 'Trần Văn Huy', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hoan@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('49bb7f91-674c-43e5-a1d6-5e8e8e50e835', 'NV-32', 'Vũ Văn Thế', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hoang.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('49bf2b41-f241-459e-a82f-8c41271d1c01', 'NV-311', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('4a0b4cf5-e029-488a-a495-faa9e9d0af24', 'NV-66', 'Ngô Tất Sơn', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'son@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('4ab6a1fe-6ceb-4b08-b4e9-eb411296b657', 'NV-126', 'Đỗ Ngọc Thúy', '1999-08-03', 0, '', NULL, '', NULL, NULL, NULL, NULL, 'thuydn@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('4e68d276-a6fb-43c2-9ef8-c96ad470a8d2', 'NV-346', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('4ef71302-e131-4aaf-b430-07d8f9ad6137', 'NV-202', 'Trần Sao Mai', '1998-04-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('5012b42a-f3e9-42b3-b8f1-d0a96f7866d5', 'NV-313', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('550f09db-c025-4ff6-bf3f-8b034d4e94c6', 'NV-422', 'Nguyễn Minh Châu', '2024-01-29', 0, '', '2024-01-29', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('55d3e75b-9d67-49b5-80ed-2a7c472ca998', 'NV-306', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('562fa9e6-52f3-4d2c-a578-8030798eb287', 'NV-342', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('571e6033-4a37-49fb-a87e-519e1520cdc0', 'NV-295', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('57400fd2-8c47-406a-b22a-7d8a216cc41d', 'NV-28', 'Vũ Văn Thế', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hoang@gmailcom', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('5894433f-463e-4d4c-a4d6-cd8efbc46a64', 'NV-208', 'Nguyễn Minh Châu', '2000-01-22', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('58dc3957-3942-4902-8c38-18fbc7e09c52', 'NV-105', 'Nguyễn Văn Anh', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9feafdd0-b6e0-11ee-9729-f8477b936e6f'),
('5de845cb-8f42-40e7-99a4-56017abacd47', 'NV-288', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('5ec48eee-53f4-4c85-b5c0-d8ab71ecc6dd', 'NV-86', 'Hoàng Thị Sao Mai', '2002-04-30', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hoangmai@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('5f60b611-7a8e-4bc2-98da-bb69d356f3f3', 'NV-24', 'Vũ Văn Thế', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hoang@gmailcom', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('61cdb3e3-c1d2-4e12-b085-51176080141b', 'NV-151', 'Trần Sao Mai', '1998-02-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('625e57a9-7bd1-4f07-ac6c-ef0900be5b3d', 'NV-209', 'Nguyễn Minh Châu', '2000-01-22', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('637d68a2-5594-4806-a38a-80ee6e98dd96', 'NV-103', 'Nguyễn Đình An', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9feafdd0-b6e0-11ee-9729-f8477b936e6f'),
('64e3874c-d6c6-4d30-98dc-317566d2197c', 'NV-46', 'Tống Mỹ Linh', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'mylinh@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('65c9d0d0-c907-444d-b5d2-ab73eda4d7df', 'NV-204', 'Trần Sao Mai', '1998-04-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('66aecc72-adfb-4c8b-8aa1-54fca9bad88a', 'NV-444', 'Đỗ Ngọc Thúy', '1999-08-03', 0, '', NULL, '', '', '', '', '', 'thuydn@gmail.com', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('679df5cb-3434-42a3-84df-4586f040f47a', 'NV-59', 'Bùi Văn Sơn', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'sonbui@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('6a3ef2fa-efe4-41e2-881c-d9b823830753', 'NV-280', 'Nguyễn Minh Châu', '2000-01-22', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('6a657e40-2384-4113-ac07-4797cf348e45', 'NV-206', 'Trần Hoàng Sao Mai', '1998-04-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('6ba15e85-3e46-4d05-9f86-b353ef38174f', 'NV-110', 'Võ Minh Đức', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9feafdd0-b6e0-11ee-9729-f8477b936e6f'),
('6befa76d-2d93-4941-8f77-97cf77c7cf1c', 'NV-162', 'Trần Sao Mai', '1998-04-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('6cde490f-2bb3-4904-a9be-79d4875f32db', 'NV-300', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('6d8ce98e-9610-4e4e-b1d9-6273c1406f54', 'NV-18', 'Trần Văn Huy', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('6f3f30fa-ed13-415e-9c27-d3ce1e8088e0', 'NV-278', 'Nguyễn Minh Châu', '2000-01-22', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('7027628e-9cfc-4a17-be21-5ec5046cb208', 'NV-61', 'Vũ Tiến Đạt', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dat188@gmailcom', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('70f432ff-0871-42e3-acc6-7e964922f0a9', 'NV-244', 'Hà Đức Chinh', '1999-01-01', 1, '', '2024-01-29', '', '', '', '', '', 'ducchinh2000@gmail.com', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('726221d4-17fb-4c73-9be1-e6bdc451030e', 'NV-230', 'Nguyễn Minh Châu', '2024-01-29', 0, '', '2024-01-29', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('73ef37b8-f2c6-42c6-95f3-715bf97f1cd6', 'NV-60', 'Lã Đức Huy', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ducngo@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('7780be3c-446a-4f3d-88f1-dae440285538', 'NV-152', 'Trần Sao Mai', '1998-02-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('77b608e6-1c9d-4d95-87ee-1aafe10f7053', 'NV-218', 'Trần Hoàng Sao Mai', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('7a11c7ee-7cec-48ff-8038-a327f5130808', 'NV-80', 'Trần Phương Chi', '2002-03-02', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('7d2b6db3-4c3f-42ef-b950-739879e90975', 'NV-210', 'Nguyễn Minh Châu', '2000-01-22', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('84ddfcbf-305e-4be6-8713-63cef72c22c4', 'NV-275', 'Nguyễn Minh Châu', '2000-01-22', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('854961d0-9c83-4df7-80e6-c90e1ff23f3e', 'NV-401', 'Nguyễn Minh Châu', '2024-01-29', 0, '', '2024-02-18', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('878ec99d-b8cf-11ee-9729-f8477b936e6f', 'NV08', 'Bùi Việt Hoàng', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'b7b8c0f7-b6dd-11ee-9729-f8477b936e6f'),
('8862c3da-55b0-410e-9d8a-ad01f5556088', 'NV-33', 'Vũ Văn Thế', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('88a1457a-4daa-457c-b65e-3fd43088142e', 'NV-50', 'Nguyễn Văn Thái Sơn', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'thaison@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('8b03664b-18ca-4e2e-9c3d-ebd590e02e69', 'NV-57', 'Ngô Tiến Đức', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ducngo@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('8b073283-030d-4103-990d-a1bea47634d1', 'NV-158', 'Trần Sao Mai', '1998-03-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('8baaae00-7fcf-4ff7-838e-d3af98e4dea0', 'NV-340', 'Hà Đức Chinh', '2000-01-01', 1, '03420987', '2024-01-29', 'Trưởng phòng', '', '', '', '', 'duc@gmail.com', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('8c1bfad8-4739-4bf3-918c-0cd61c7bb832', 'NV-310', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('8ce40952-951f-476a-ba33-021017515a61', 'NV-113', 'Trương Thành Hưng', '1998-02-04', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('8d7b2575-8892-4fe2-a7ee-6030e56e8c00', 'NV-34', 'Vũ Văn Thế', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('91180c92-b578-4d33-829a-f2c78566d066', 'NV-15', 'Trần Văn Huy', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('91ed89da-65be-406e-b860-85102a5ccb6d', 'NV-116', 'Đặng Trường Khánh', '1998-02-04', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('92b8f560-e11b-48ba-b78b-17ad13050569', 'NV-95', 'Đào Thu Hằng', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'thuhang1905@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('93cece29-ca4b-4bd6-847c-231272106130', 'NV-351', 'Nguyễn Minh Châu', NULL, 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('95b8c2e9-d024-403a-a297-7060d583d756', 'NV-271', 'Nguyễn Minh Châu', '2000-01-22', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('95be8cf2-7381-4bb8-889c-843803ae7471', 'NV-350', 'Nguyễn Minh Châu', NULL, 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('969d768b-8478-4003-8d4a-28d3cc2db1c0', 'NV-17', 'Trần Văn Huy', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('96e2d61d-84f2-42c4-a6f4-8530f562fc3d', 'NV-246', 'Trần Hoàng Sao Mai', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('97ffff47-0f9c-487c-a81a-fb985628d587', 'NV-277', 'Nguyễn Minh Châu', '2000-01-22', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('983859d3-b08c-47b2-bf5e-4ee631dd6f0b', 'NV-82', 'Trần Phương Chi', '2002-03-02', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('98510c5d-06b9-4d35-b8e6-1441c0a17ccb', 'NV-98', 'Phạm Đình Khiêm', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9febd839-b6e0-11ee-9729-f8477b936e6f'),
('98b6e672-d9e9-4fff-acf8-43c2b057244e', 'NV-111', 'Võ Minh Đức', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('992c2c8f-8a6f-46e7-8716-336aa2b40e2a', 'NV-109', 'Võ Minh Đức', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9feafdd0-b6e0-11ee-9729-f8477b936e6f'),
('993bf903-d5d5-40f3-8573-c5a5fdcc3444', 'NV-255', 'Trần Văn Thế', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'thenv@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('99ac3b54-390a-4ac5-9a8c-b0aabcb746f2', 'NV-155', 'Trần Sao Mai', '1998-03-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('9b68a871-5683-4ea5-85b5-4bb53a12dc0e', 'NV-321', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('9fec8264-b6e0-11ee-9729-f8477b936e6f', 'NV02', 'Nguyễn Văn Bằng', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'b7b8c0f7-b6dd-11ee-9729-f8477b936e6f'),
('a028c4d9-95a4-4f8c-b4d1-ee744ad0b47b', 'NV-14', 'Trần Văn Huy', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('a27d109d-9750-4178-992c-06558e5d9c8d', 'NV-318', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('a3281fb2-707a-4ac9-ba6d-8a06e2f79712', 'NV-291', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('a337039e-cc3a-47be-bfa3-17e252922b12', 'NV-247', 'Nguyễn Minh Châu', '2024-01-29', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('a4158f06-e9cf-4d3b-99c4-b34c0bdee10b', 'NV-426', 'Nguyễn Minh Châu', '2024-01-29', 0, '', '2024-01-29', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('a79da338-3ff0-44ea-a6a1-bf9923e3ae12', 'NV-92', 'Đào Thu Hằng', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'thuhang1905@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('a7e26cd2-e364-45b5-a875-c48dfe937f43', 'NV-211', 'Đỗ Ngọc Thúy', '2024-01-29', 0, '', '2024-01-29', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('a8d28778-a1b5-4f16-b7d9-90ef12d025ec', 'NV-128', 'Đỗ Ngọc Thúy', '1999-08-03', 0, '', NULL, '', NULL, NULL, NULL, NULL, 'thuydn@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('a8e2f874-888f-436a-8cf9-b752276b6e8d', 'NV-101', 'Phạm Thái Dương', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9febd839-b6e0-11ee-9729-f8477b936e6f'),
('a99cecd6-cdd7-48b8-b927-cefbae095ca5', 'NV-260', 'Ngô Bảo Châu', NULL, 1, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('aa388431-4474-4116-b798-0a6ab96d92c8', 'NV-107', 'Nguyễn Minh Đức', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9feafdd0-b6e0-11ee-9729-f8477b936e6f'),
('ab0ae27f-00a1-404b-a361-2448dcdf7396', 'NV-293', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('ac3f974c-db16-40ef-9cb4-f85da30821b3', 'NV-159', 'Trần Sao Mai', '1998-03-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('ad4bba37-1e97-4aab-a17a-449694058499', 'NV-299', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('ae7d14f0-a1ad-4113-9e93-403c028ed43b', 'NV-42', 'Trần Quốc Tuấn', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('b1682009-f599-4d22-b81b-587832777622', 'NV-214', 'Trần Hoàng Sao Mai', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('b39a17ac-c50c-4556-b64a-d9b12c27e3a1', 'NV-298', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('b3aa9edc-a5b3-4e8c-976c-385954baa561', 'NV-130', 'Đỗ Ngọc Thúy', '1999-08-03', 0, '', NULL, '', NULL, NULL, NULL, NULL, 'thuydn@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('b46995e4-9a72-4291-a470-00ba6a4c9b03', 'NV-274', 'Nguyễn Minh Châu', '2000-01-22', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('b52c7588-783f-483c-857b-8dd3cedf0fbd', 'NV-241', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-29', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('b5e08240-eb0b-4261-b412-0dd391ed72ab', 'NV-40', 'Trần Quốc Tuấn', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'tuan@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('b684dc9b-a08c-4f57-8a6e-c4e04529f510', 'NV-106', 'Nguyễn Văn Anh', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9feafdd0-b6e0-11ee-9729-f8477b936e6f'),
('b80b0cf6-66ad-4aa5-9c60-c92be3feafb2', 'NV-91', 'Đào Thu Hằng', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'thuhang1905@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('b82f9633-1c9b-45e6-b41c-444d295ec38e', 'NV-93', 'Đào Thu Hằng', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'thuhang1905@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('b8324db2-15ea-45f4-9f48-e327a7da1d00', 'NV-283', 'Nguyễn Minh Châu', '2000-01-22', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('b94a85b4-8679-41cb-9930-5bc50fff9bd3', 'NV-282', 'Nguyễn Minh Châu', '2000-01-22', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('b96716c4-8a1f-4f89-8c70-d0f0f93f0b0c', 'NV-314', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('b9b000b1-1322-41f2-b93a-9a434f3504df', 'NV-118', 'Đặng Trường Khánh', '1998-02-04', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('ba763e6a-e7d8-44d4-bebc-06c428daa188', 'NV-94', 'Đào Thu Hằng', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'thuhang1905@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('ba9506f0-91d2-4d82-a288-28e6aa1a739b', 'NV-279', 'Nguyễn Minh Châu', '2000-01-22', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('bb2e0a4c-d0a4-4951-bae6-13ac445b0152', 'NV-315', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('bc832841-e90d-413b-8b82-336adce4e2f9', 'NV-301', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('bcf960bd-b7fd-44fa-9dbe-9bab0de0cacc', 'NV-319', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('bd54b232-cdd6-46c8-9156-ef65759d8dbe', 'NV-347', 'Đỗ Ngọc Thúy', '1999-01-01', 1, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('bd79a86a-dee4-4d8b-9856-080b05dcdf04', 'NV-276', 'Nguyễn Minh Châu', '2000-01-22', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('be1b6bb9-b8cf-11ee-9729-f8477b936e6f', 'NV11', 'Bùi Việt Hoàng', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'b7b8c0f7-b6dd-11ee-9729-f8477b936e6f'),
('be521e85-e32e-4d8e-b575-3ecd63f7719b', 'NV-63', 'Mai Trung Lâm', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'thenv@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('c0d86f98-60f4-46bf-9bcf-c89697ad2c93', 'NV-316', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('c201c3ad-f8b8-4a1b-aed6-b0eb74da5f30', 'NV-117', 'Đặng Trường Khánh', '1998-02-04', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('c3ef83c8-b69f-4e5b-970a-628150f5c069', 'NV-70', 'Ngô Tất Sơn', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'son@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('c44066bf-7748-407f-81a7-a9288d5a51a6', 'NV-305', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('c4c709c9-6550-4f8e-8095-424eb675fe47', 'NV-43', 'Trần Quốc Tuấn', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'tuan@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('c88828b2-7ab8-478a-9d37-af305145244d', 'NV-102', 'Nguyễn Đình An', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9febd839-b6e0-11ee-9729-f8477b936e6f'),
('ca9a6906-9bf7-436f-a7c0-0dfbbb7aa0c8', 'NV-129', 'Đỗ Ngọc Thúy', '1999-08-03', 0, '', NULL, '', NULL, NULL, NULL, NULL, 'thuydn@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('cb0c6936-b368-481f-9bc3-5f3b8f7bb235', 'NV-36', 'Vũ Văn Hiệu', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('cc4ecde6-6edc-49be-a1d2-b513cb9f40f0', 'NV-85', 'Hoàng Thị Sao Mai', '2002-04-30', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hoangmai@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('ce9c5280-b936-11ee-9729-f8477b936e6f', 'NV-11', 'Bùi Việt Hoàng', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9febd839-b6e0-11ee-9729-f8477b936e6f'),
('d146a668-ce57-4351-b0e5-69144aea0dfb', 'NV-83', 'Trần Phương Chi', '2002-03-02', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('d16fc343-3966-400d-b3aa-1be82968ca88', 'NV-38', 'Vũ Văn Hiệu', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hieu@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('d18e5546-94a4-4835-a6fb-24d791aa3ad4', 'NV-402', 'Đỗ Ngọc Thúy', '2024-01-29', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('d33a5f96-23f3-4fe4-9bf1-9cbb16f66796', 'NV-81', 'Trần Phương Chi', '2002-03-02', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('d38a67f6-b8ce-11ee-9729-f8477b936e6f', 'NV10', 'Bùi Việt Hoàng', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'b7b8c0f7-b6dd-11ee-9729-f8477b936e6f'),
('d3a943ee-66b5-4024-ae34-41730459fddc', 'NV-421', 'Đào Trung Quân', NULL, 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('d4a75447-224b-4d29-a001-20edd835ebb1', 'NV-281', 'Nguyễn Minh Châu', '2000-01-22', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('d5476e13-77ef-45f1-b61e-954c67a49464', 'NV-309', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('d9dbfc07-381a-485c-8a91-0b3db055eb85', 'NV-220', 'Nguyễn Minh Châu', '2024-01-29', 0, '', '2024-01-29', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('da18f310-6783-4a5b-a683-d4584670edbd', 'NV-424', 'Đỗ Ngọc Thúy', '2024-01-29', 0, '', '2024-01-29', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('da573d81-3094-4d57-b3de-64a94cc1e758', 'NV-320', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('da5cf33b-a66a-4735-afe8-2f9483e5bdf5', 'NV-272', 'Nguyễn Minh Châu', '2000-01-22', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('db0034c0-47cc-4316-89a8-0237d29c1b5c', 'NV-96', 'Ngô Mạnh Hùng', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9fec44ae-b6e0-11ee-9729-f8477b936e6f'),
('db955ed0-6214-4c04-8ca8-df949a91d2d6', 'NV-87', 'Hoàng Thị Sao Mai', '2002-04-30', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hoangmai@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('dcd60095-dddd-42d0-b00d-d86f981884a4', 'NV-16', 'Trần Văn Huy', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('dda7c7ab-23b6-4f98-a7d2-0d0c171da60d', 'NV-423', 'Đỗ Ngọc Thúy', '2024-01-29', 0, '', '2024-02-06', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('de4f2c0b-82af-4f90-ad00-1aef6da9e7a5', 'NV-317', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('de5be872-b8ce-11ee-9729-f8477b936e6f', 'NV09', 'Bùi Việt Hoàng', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'b7b8c0f7-b6dd-11ee-9729-f8477b936e6f'),
('e0da1cdd-25d5-4f5e-a920-e7f309fab68d', 'NV-343', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('e1de7d45-1735-4a51-8622-2c8a5e902944', 'NV-297', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('e37d479d-2588-4605-890e-ca720eb383c0', 'NV-104', 'Nguyễn Trọng Anh', '2002-05-19', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9feafdd0-b6e0-11ee-9729-f8477b936e6f'),
('e386dfe9-9066-409e-ac6c-4523f4c2c4d3', 'NV-150', 'Trần Sao Mai', '1998-02-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('e4cd7471-ed4d-428d-a1d8-77cefcdb6327', 'NV-51', 'Bùi Văn Sơn', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'sonbui@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('e5a71c39-18ee-4bd1-afce-754541830829', 'NV-294', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('e764044a-c284-4035-9c10-a343c483c42f', 'NV-404', 'Đào Trung Hải', NULL, 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('e7a7fda5-5d7a-4ae7-92a6-6f9a3aee908e', 'NV-71', 'Ngô Tất Sơn', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('e7be79fc-77c0-4e51-b3c9-a4e11b4ab158', 'NV-131', 'Nguyễn Minh Châu', '1999-08-03', 0, '', NULL, '', NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('e83b98ed-51a3-4bf1-91b0-558b69d861cb', 'NV-22', 'Ngô Bá Khá', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hoan@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('ea758884-3326-414c-8022-34823a288c7c', 'NV-292', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('ea83ca23-a1e3-4517-aa22-b1aefeaebf15', 'NV-308', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('eb097eb0-edf1-4d9b-9680-5c9e8d045a0d', 'NV-270', 'Nguyễn Minh Châu', '2000-01-22', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('eb0cef01-96a9-400c-9ef3-351b459ecd06', 'NV-49', 'Bùi Văn Sơn', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('eb391f85-08c4-44dd-a464-44590ca2913c', 'NV-23', 'Vũ Văn Thế', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'hoang@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('eb9622dc-54f6-4d18-9017-11463256060b', 'NV-345', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('ebb51412-731e-4e5e-9120-33ec5bd5cf50', 'NV-060', 'Vũ Văn Thế 25', NULL, 1, '', NULL, '', NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('f0e32a46-9be1-43dc-908b-86c0553d23b9', 'NV-201', 'Trần Sao Mai', '1998-04-10', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('f0f2dc52-9067-4e70-a3c5-1faae13a3a03', 'NV-44', 'Vương Xuân Tuấn', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'tuanvx@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('f117ba7e-51a8-4269-b931-49f444ed3e08', 'NV-39', 'Trần Quốc Tuấn', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'tuan@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('f1477284-4b32-4a53-b13a-b0302b5bb46a', 'NV-13', 'Trần Văn Huy', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('f46c6a97-8066-4ee0-b561-8fdd3c7ceb4e', 'NV-56', 'Nguyễn Khánh Huyền', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'khanhhuyen@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('f600c774-4581-40f8-a6bb-5f43d614504c', 'NV-240', 'Nguyễn Minh Châu', '2024-01-29', 0, '', '2024-01-29', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('f655e985-16ac-4b3e-a91e-f7c8ee95f842', 'NV-304', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('f6bde0f8-ed60-4aba-b8ef-963e258ef449', 'NV-115', 'Trương Thành Hưng', '1998-02-04', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('f7c15507-de91-4056-81e8-001dec5560b4', 'NV-250', 'Nguyễn Minh Châu', '2024-01-29', 0, '', NULL, '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('f91a240a-db2a-4ca5-b4d6-95cabcb66b93', 'NV-219', 'Nguyễn Minh Châu', '2024-01-29', 0, '', '2024-01-29', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('f970c857-c2bf-4f9a-a7f9-859a967c129a', 'NV-217', 'Nguyễn Minh Châu', '2024-01-29', 0, '', '2024-01-29', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('f9f855ee-56d4-46df-b29c-f49c8d5566db', 'NV-215', 'Trần Văn Huy', '2024-01-01', 1, '', '2024-01-29', '', '', '', '', '', 'hoan@gmail.com', '', '', '', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('ff05bd6b-0274-4e7e-94c2-fb9798df477f', 'NV-289', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('ff30adef-4192-404c-8a00-2944f4570b4a', 'NV-290', 'Hà Đức Chinh', '1999-01-01', 1, '03420987', '2024-01-30', 'Trưởng phòng', 'Thái Bình', 'Thái Bình', '09892370', '', 'ducchinh2000@gmail.com', '0928398473', 'MBBank', 'Thái Bình', NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f'),
('ff688daf-7e92-4a81-bbf7-1d13b2d7bc0d', 'NV-141', 'Đặng Trường Khánh', '1998-02-04', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205aa1b3-b6e0-11ee-9729-f8477b936e6f'),
('ffd32d66-cec2-469d-a284-2abac2d5f6f7', 'NV-84', 'Hoàng Thị Sao Mai', '2002-04-30', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '205a5f6a-b6e0-11ee-9729-f8477b936e6f');

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;